name: 'mini_lakehouse'
version: '1.0'
config-version: 2

profile: 'mini_lakehouse'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  mini_lakehouse:
    +materialized: view
    staging:
      +schema: stg
      +materialized: view
    core:
      +schema: core
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
