name: 'mini_lakehouse'
version: '1.0'
config-version: 2

profile: 'mini_lakehouse'

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  staging:
    +schema: stg
    +materialized: view
    real:
      +tags: ["real"]
    simulated:
      +tags: ["simulated"]

  core:
    +schema: core
    +materialized: table
    real:
      +tags: ["real"]
    simulated:
      +tags: ["simulated"]

  marts:
    +schema: marts
    +materialized: table
    real:
      +tags: ["real"]
    simulated:
      +tags: ["simulated"]

seeds:
  +schema: seeds
  +materialized: seed
  bilanci_comunali_sample:
    +column_types:
      codice_comune: bigint
      nome_comune: text
      anno: bigint
      entrate_tributarie: bigint
      spese_correnti: bigint

  bilanci_voci_sample:
    +column_types:
      codice_comune: bigint
      nome_comune: text
      anno: bigint
      codice_siope: text
      descrizione_siope: text
