name: 'mini_lakehouse'
version: '1.0'
config-version: 2

profile: 'mini_lakehouse'

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analysis"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
  mini_lakehouse:

    staging:
      +materialized: view

      real:
        +schema: stg_real
        +tags: ["real"]

      simulated:
        +schema: stg_simulated
        +tags: ["simulated"]

    core:
      +materialized: table

      real:
        +schema: core_real
        +tags: ["real"]

      simulated:
        +schema: core_simulated
        +tags: ["simulated"]

    marts:
      +materialized: table

      real:
        +schema: marts_real
        +tags: ["real"]

      simulated:
        +schema: marts_simulated
        +tags: ["simulated"]

seeds:
  mini_lakehouse:
    +schema: seeds
    +materialized: seed

    bilanci_comunali_sample:
      +column_types:
        codice_comune: BIGINT
        nome_comune: TEXT
        anno: BIGINT
        entrate_tributarie: BIGINT
        spese_correnti: BIGINT

    bilanci_voci_sample:
      +column_types:
        codice_comune: BIGINT
        nome_comune: TEXT
        anno: BIGINT
        codice_siope: TEXT
        descrizione_siope: TEXT
