version: 2

models:
  - name: core_bilanci_comuni
    description: >
      Modello core con i bilanci dei comuni italiani, validato e ripulito.
    columns:
      - name: codice_comune
        tests:
          - not_null
      - name: nome_comune
        description: Nome formattato del comune
        tests:
          - not_null
          - dbt_utils.not_empty_string
      - name: anno
        description: Anno di riferimento del bilancio
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 2000
              max_value: 2025
      - name: entrate
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_greater_than:
              value: 0
      - name: spese
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_greater_than:
              value: 0

    tests:
      - dbt_expectations.expect_column_pair_values_to_be_in_set:
          column_A: entrate
          column_B: spese
          value_set:
            - [">=", "<="]  # entrate >= spese
