version: 2

models:
  - name: core_bilanci_comuni
    description: Modello core con i bilanci dei comuni italiani, validato e ripulito.
    columns:
      - name: codice_comune
        tests:
          - not_null

      - name: nome_comune
        description: Nome formattato del comune
        tests:
          - not_null
          - dbt_utils.not_empty_string

      - name: anno
        description: Anno di riferimento del bilancio
        tests:
          - not_null

      - name: entrate
        tests:
          - not_null

      - name: spese
        tests:
          - not_null
