version: 2

models:
  - name: core_bilanci_comuni
    description: "Modello core con casting e filtri base sui bilanci."
    columns:
      - name: codice_comune
        description: "Codice del comune"
        tests:
          - not_null
      - name: anno
        description: "Anno del bilancio"
        tests:
          - not_null
      - name: nome_comune
        description: "Nome del comune con iniziali maiuscole"
      - name: entrate
        description: "Entrate tributarie castate"
      - name: spese
        description: "Spese correnti castate"
      - name: id_hash
        description: "Identificatore univoco hash"
        tests:
          - unique
