version: 2

models:
  - name: stg_bilanci_comuni
    description: "Staging dei dati grezzi da bilanci comunali, con normalizzazione nomi e lowercase."
    columns:
      - name: codice_comune
        description: "Codice identificativo del comune"
        tests:
          - not_null
      - name: nome_comune
        description: "Nome del comune in formato normalizzato"
      - name: anno
        description: "Anno di riferimento del bilancio"
        tests:
          - not_null
      - name: entrate_tributarie
        description: "Entrate tributarie del comune"
        tests:
          - not_null
      - name: spese_correnti
        description: "Spese correnti sostenute"
        tests:
          - not_null
