version: 2

models:
  - name: agg_entrate_per_categoria
    description: "Aggregazione delle entrate per categoria SIOPE livello 1, per anno e comune."
    config:
      contracts:
        enforced: true
      tags: ["simulated"]
    columns:
      - name: categoria
        description: "Codice categoria SIOPE (es. E1, E101, …)"
        type: string
        tests: [not_null]

      - name: descrizione
        description: "Descrizione categoria SIOPE"
        type: string
        tests: [not_null]

      - name: numero_movimenti
        description: "Numero di movimenti per questa categoria"
        type: integer
        tests: [not_null]

      - name: totale_entrate
        description: "Totale delle entrate tributarie per categoria"
        type: double
        tests: [not_null]

  - name: fact_bilanci_comunali
    description: "Fatti aggregati annuali per comune, con flag e indicatori di qualità."
    config:
      contracts:
        enforced: true
      tags: ["simulated"]
    columns:
      - name: codice_comune
        description: "Codice ISTAT del comune."
        type: string
        tests: [not_null]

      - name: nome_comune
        description: "Nome del comune."
        type: string
        tests: [not_null]

      - name: anno
        description: "Anno di riferimento."
        type: integer
        tests: [not_null]

      - name: totale_entrate
        description: "Somma annuale delle entrate tributarie."
        type: double
        tests: [not_null]

      - name: totale_spese
        description: "Somma annuale delle spese correnti."
        type: double
        tests: [not_null]

      - name: saldo
        description: "Differenza tra entrate e spese."
        type: double
        tests: [not_null]

      - name: flag_dato_incompleto
        description: "Flag booleano se mancano dati per entrate o spese."
        type: boolean
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: indicatore_affidabilita
        description: "Indicatore euristico di affidabilità del dato (0-100)."
        type: double
        tests: [not_null]

  - name: mart_finanza_locale
    description: "Tabella aggregata bilanci per comune e anno con flag di anomalia."
    config:
      contracts:
        enforced: true
      tags: ["simulated"]
    columns:
      - name: codice_comune
        description: "Codice ISTAT del comune"
        type: string
        tests: [not_null]

      - name: nome_comune
        description: "Denominazione ufficiale del comune"
        type: string
        tests: [not_null]

      - name: anno
        description: "Anno di esercizio"
        type: integer
        tests: [not_null]

      - name: entrate_tributarie
        description: "Entrate totali registrate"
        type: double
        tests: [not_null]

      - name: spese_correnti
        description: "Spese totali registrate"
        type: double
        tests: [not_null]

      - name: saldo
        description: "Differenza entrate - spese"
        type: double
        tests: [not_null]

      - name: flag_anomalia
        description: "True se presente almeno una anomalia audit"
        type: boolean
        tests: [not_null]
